// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bgxfkkkevlzwnmghfpkf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJneGZra2tldmx6d25tZ2hmcGtmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU0ODYzNjgsImV4cCI6MjA2MTA2MjM2OH0.qdbmhZJH_HjtF5AOaYyJiHkS8wuqtyYwtFIljWr37H8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);